spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/flow_engine?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 19940114
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
  config: classpath:logback-spring.xml

