server:
  port: 8080

spring:
  application:
    name: flow-rest
  datasource:
    url: jdbc:mysql://localhost:3306/flowengine
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  groovy.template.check-template-location: false

logging:
  level:
    root: info
    org.springframework.web.filter: debug

