const myflow ={
    "type":"PROCESS",
    "id":"wms-flow-lineRequirement",
    "name":"线边拉料需求单业务流",
    "elements":[
        {
            "id":"start",
            "type":"START",
            "name":"开始节点\n(line.createPullRequireBatch)",
            "config":{}
        },
        {
            "id":"line1",
            "name":"",
            "type":"SEQUENCE_FLOW",
            "sourceId":"start",
            "targetId":"decision1"
        },
        {
            "id":"decision1",
            "type":"DECISION",
            "name":"单据类型决策",
            "config":{
                
            }
        },
        {
            "id":"line2",
            "type":"SEQUENCE_FLOW",
            "sourceId":"decision1",
            "targetId":"outward_create_and_srm_send",
            "config":{
                "condition":"pullMode=='JIS'&&supplyType==2"
            }
        },
        {
            "id":"outward_create_and_srm_send",
            "type":"SERVICE_TASK",
            "name":"创建外排单并下发srm\n(inbound.createOutward)",
            "config":{
                "implementation":"JavaBean",
                "beanName":"outwardCreateService"
            }
        },
        {
            "id":"line3",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_create_and_srm_send",
            "targetId":"outward_decision1"
        },
        {
            "id":"outward_decision1",
            "type":"DECISION",
            "name":"外排单创建结果判断",
            "config":{
                
            }
        },
        {
            "id":"line4",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_decision1",
            "targetId":"requirement_update_status_EXCEPTION",
            "config":{
                "condition":"!outwardCreateResult"
            }
        },
        {
            "id":"requirement_update_status_EXCEPTION",
            "type":"SERVICE_TASK",
            "name":"修改需求单状态：异常\n(line.updateStatus)",
            "config":{
                "implementation":"JavaBean",
                "beanName":"requirementUpdateStatusService"
            }
        },
        {
            "id":"line5",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_decision1",
            "targetId":"requirement_update_status_GENERATE_PICKING",
            "config":{
                "condition":"outwardCreateResult"
            }
        },
        {
            "id":"requirement_update_status_GENERATE_PICKING",
            "type":"SERVICE_TASK",
            "name":"修改需求单状态：已生成拣配单\n(inbound.createOutward)",
            "config":{
                "implementation":"JavaBean",
                "beanName":"requirementUpdateStatusService"
            }
        },
        {
            "id":"line6",
            "type":"SEQUENCE_FLOW",
            "sourceId":"requirement_update_status_GENERATE_PICKING",
            "targetId":"outward_srm_result_callback"
        },
        {
            "id":"outward_srm_result_callback",
            "type":"USER_TASK",
            "name":"外排单SRM下发成功回调(人工)\n(inbound.srmSuccess)",
            "config":{
            }
        },
        {
            "id":"line7",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_srm_result_callback",
            "targetId":"outward_update_status_SRM"
        },
        {
            "id":"line7-1",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_update_status_SRM",
            "targetId":"requirement_update_status_SEND_PICKING"
        },
        {
            "id":"outward_update_status_SRM",
            "type":"SERVICE_TASK",
            "name":"修改外排单状态：已下发SRM\n(inbound.outwardOrderResultSend)",
            "config":{
                "implementation":"JavaBean",
                "beanName":"requirementUpdateStatusService"
            }
        },
        {
            "id":"requirement_update_status_SEND_PICKING",
            "type":"SERVICE_TASK",
            "name":"修改需求单状态：已下发拣配单\n(inbound.outwardOrderResultSend)",
            "config":{
                "implementation":"JavaBean",
                "beanName":"requirementUpdateStatusService"
            }
        },
        {
            "id":"line7-2",
            "type":"SEQUENCE_FLOW",
            "sourceId":"requirement_update_status_SEND_PICKING",
            "targetId":"outward_pda_receive"
        },
        {
            "id":"outward_pda_receive",
            "type":"USER_TASK",
            "name":"点收(人工)\n(inbound.save)",
            "config":{
            }
        },
        {
            "id":"line8",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_pda_receive",
            "targetId":"outward_decision2"
        },
        {
            "id":"outward_decision2",
            "type":"DECISION",
            "name":"点后后处理决策",
            "config":{
            }
        },
        {
            "id":"line9",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_decision2",
            "targetId":"requirement_update_status_FEED_FINISHED",
            "config":{
                "condition":"requireLevel==1&&onlineWay==0"
            }
        },
        {
            "id":"requirement_update_status_FEED_FINISHED",
            "type":"SERVICE_TASK",
            "name":"修改需求单状态：上料完成",
            "config":{
                "implementation":"JavaBean",
                "beanName":"requirementUpdateStatusService"
            }
        },
        {
            "id":"line10",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_decision2",
            "targetId":"requirement_update_status_PICKING_FINISHED",
            "config":{
                "condition":"!(requireLevel==1&&onlineWay==0)"
            }
        },
        {
            "id":"requirement_update_status_PICKING_FINISHED",
            "type":"SERVICE_TASK",
            "name":"修改需求单状态：拣料完成",
            "config":{
                "implementation":"JavaBean",
                "beanName":"requirementUpdateStatusService"
            }
        },
        {
            "id":"line11",
            "type":"SEQUENCE_FLOW",
            "sourceId":"requirement_update_status_PICKING_FINISHED",
            "targetId":"outward_pda_take"
        },
        {
            "id":"outward_pda_take",
            "type":"USER_TASK",
            "name":"已取料(人工)",
            "config":{
            }
        },
        {
            "id":"line12",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_pda_take",
            "targetId":"requirement_update_status_TAKE"
        },
        {
            "id":"requirement_update_status_TAKE",
            "type":"SERVICE_TASK",
            "name":"修改需求单状态：已取料",
            "config":{
                "implementation":"JavaBean",
                "beanName":"requirementUpdateStatusService"
            }
        },
        {
            "id":"outward_pda_done",
            "type":"USER_TASK",
            "name":"上料完成(人工)",
            "config":{
            }
        },
        {
            "id":"line16",
            "type":"SEQUENCE_FLOW",
            "sourceId":"requirement_update_status_TAKE",
            "targetId":"outward_pda_done"
        },
        {
            "id":"line13",
            "type":"SEQUENCE_FLOW",
            "sourceId":"outward_pda_done",
            "targetId":"end"
        },
        {
            "id":"line14",
            "type":"SEQUENCE_FLOW",
            "sourceId":"requirement_update_status_FEED_FINISHED",
            "targetId":"end"
        },
        {
            "id":"line15",
            "type":"SEQUENCE_FLOW",
            "sourceId":"requirement_update_status_EXCEPTION",
            "targetId":"end"
        },
        {
            "id":"end",
            "name":"结束节点",
            "type":"END"
        }
    ]
}